[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python bot.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[environments.production.variables]
RAILWAY_ENVIRONMENT = "production" 